apiVersion: v1
kind: Service
metadata:
  name: my-service1
spec:
  selector:
    app: my-app1
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 8080  # Container port